# step 1: NAME of workflow
name : Hello World

# step 2 :EVENTS, which tell us when to trigger this workflow
on:
  push:
    branches: [main] #we can mention multiple branches

#step 3: JOB, this tell us once the even is triggred where to run the job
job:
  demo:
     runs-on: ubuntu-latest # what or which server should be spinned up by github to run the job

     # step4: each job should have the STEP, what need to be executed
     step:
       - name: Greetings
         run: echo "Hello World" # shell script that needs ro be executed